spring.application.name=agent-backend
server.port=8081

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.chat.options.temperature=0.2

flight.api.base-url=http://13.53.166.181:8080
flight.api.username=admin
flight.api.password=1234